# https://github.com/jesseduffield/lazygit/blob/v0.55.1/docs/Config.md
keybinding:
  universal:
    gotoTop: ''
    gotoBottom: ''
    nextTab: '>'
    prevTab: <
git:
  paging:
    colorArg: always
  branchLogCmd: "git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%C(bold blue)<%an>%Creset' --abbrev-commit"
